version: "3"
services:
  mariadb:
    image: mariadb:latest
    # image: mariadb/columnstore:latest
    security_opt:
      - seccomp:unconfined  
    network_mode: host
    environment:
      USE_S3_STORAGE: 0
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive:
    image: hive
    restart: unless-stopped
    ports:
      - 9083:9083
